env:
  global:
    - REPO_DIR=tesseract-src
    - BUILD_COMMIT=215866151e774972c9502282111b998d7a053562
    - BUILD_DEPENDS=
    - TEST_DEPENDS=
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - secure: "fs6r5FYVcWbMMihWWfQZESyrLvcv06aj4rxai8JTbQUBavB0W7CUDrWRUeu53Gt7rEk7XXn4YuSdaXJa1qQx0DVg31E5cZ/ZuuA/t2F6DCfv6RffRBZtpbZXXWK4WnLxia0CetTbKpY1l4cpoV38pcFeTUyqI38GctY8SjqxLNMm8PJ1kSgiYs+3a0sjI/7ddtbmnsmhxsy6/nGBzbfAxdUutXgEqfRPpALpqCxQgVrR0jbr2l4BH6jUwtlhXp9GnofYou+uOrSZh0tmO4MUWRFHTRP2dC/JsGeANE3dg6bAt+U8RrGcJYXM7eneuVdBsG6CTzVz8TACirRgde/bXn7JIby4YS8tGi+TN1UDPBVi22M+4JW4YQGcKVMIQqoOikqCLGE3Ike5JI71VAfKMQW9MOrg9iwb3/ZJlT9cqdcCN3nT0IeYdGSrrzuG6oggN+19OOEW2ow18n4PJnyDnTmMdsYjfWBC7y/+9eEuhzIgoBJRCnKdX/9QP703PtOPxtVu/yWQVC5F9BFGtwlqN2rS00Xd6bmjmnqUYrZz4VNNeM/GQGrPMZ986maykWRD7yEvy2ngwyuu8Y/OzF3DEV/ptpDt0no6tPP4x8L/mSHOslTZv0mMtmZV182Lobq87RM8ALm5J++FcZpRagm0IQkNiJpaErTlrI4oCiVK3dg="
    - secure: "Bj0dUlBfOt1MpkJZYGIo7TzyvwJJBpxn+huerS8DzvY9yUYDhxyMxTPIbx7eiN4ovRF3P4nvuowyE8W24fne6dM4XfSjh5+3ktW8AqwbALZ3VhHs8HH1zPkkCRONcBPjuwu8XF6j7ZHu033r17H+4QJWKnabgC9bsNDy2jA+N/0tEk+ImsGakqugvGyEYXrRp4oQiyJ9Zvo8LlA18oB0s9ybjnrV9vQwMuOxtL+HEd7MRiJ5pLymjBt/i/JwVPoADyg2KlOHDQT/+ChxlRTF3Ee7Sf8Q5VBQGCP7mdy0aQXDmo0baFKSBjRIIUdGlNYI4PBPmX9Tbt1p/SQcsFm7M5bkp/Z3orZdBB3YjuH+hevOWjOki8sFTL297y1r5Xk1v1bgKl6NlCsSan4uWgBsoZpmAJI04uLGtaX+Dare1ybmxwT8dORyncR7x/bXgDbwafWjOruQkrfhrMcPA33IDBEvp6uAmnLlW+eTgZWq2h79IlWNpqWQNs2lZ2OQM8NvNqnK47fOlVltUWLVamrx+l5JHAi7bi5C39KgKb1KxekdGGpbw20dEqRT3Fc5XI5NYt3xyEI8Mz5V/MUnPEWqykbGXffIJBGjOPGwO4NlowRmzsprIx2ypA9AX5TH/rLq7WPixzT6JFu9bLXLzf55AY9Xt+ErpJycQO/GFjRygP8="

language: python
python: 3.5
sudo: required
dist: trusty
services: docker

matrix:
  exclude:
    # Exclude the default Python 3.5 build
    - python: 3.5
  include:
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT_NAME=linux
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=2.7
  #        - UNICODE_WIDTH=16
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=2.7
  #        - PLAT=i686
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=2.7
  #        - PLAT=i686
  #        - UNICODE_WIDTH=16
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.3
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.3
  #        - PLAT=i686
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.4
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.4
  #        - PLAT=i686
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.5
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.5
  #        - PLAT=i686
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.6
  #    - os: linux
  #      env:
  #        - MB_PYTHON_VERSION=3.6
  #        - PLAT=i686
    - os: osx
      language: generic
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT_NAME=macosx
  #    - os: osx
  #      language: generic
  #      env:
  #        - MB_PYTHON_VERSION=3.4
  #    - os: osx
  #      language: generic
  #      env:
  #        - MB_PYTHON_VERSION=3.5
  #    - os: osx
  #      language: generic
  #      env:
  #        - MB_PYTHON_VERSION=3.6
  #    - os: osx
  #      language: generic
  #      env:
  #        - MB_PYTHON_VERSION=pypy-5.7

before_install:
  - source multibuild/common_utils.sh
  - source multibuild/travis_steps.sh
  - before_install

install:
  - make wheel

script:
  - install_run $PLAT

after_success:
  - make distribute
