language: python
sudo: required
services: docker

script:
  - make

after_success:
  - make distribute

matrix:
  include:
    - os: osx
      python: "2.7"
    - os: osx
      python: "3.6"
    - os: linux
      python: "2.7"
    - os: linux
      python: "3.6"
